version: '3.7'
services:
  minecraft:
    environment:
      MEMORY: 6G
      SERVER_NAME: ${SERVER_NAME}
      MAX_PLAYERS: 100
      MOTD: 'Servidor da Unicamp!'
      ICON: 'https://i.imgur.com/rW6DkF6.png'
      OPS: GustavoHM
